version: '3.8'

services:
  db:
    image: kanadome/hackathon_vol8_team21-db:latest
    build:
      context: ./
      dockerfile: infra/dockerfiles/prod/db.Dockerfile
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
      
  backend:
    image: kanadome/hackathon_vol8_team21-backend:latest
    tty: true
    depends_on:
      - db
    build:
      context: ./ 
      dockerfile: infra/dockerfiles/prod/backend.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  frontend:
    image: kanadome/hackathon_vol8_team21-frontend:latest
    build:
      context: ./
      dockerfile: infra/dockerfiles/prod/frontend.Dockerfile
    volumes:
      - ./frontend/app:/app
    networks:
      - app-network
    ports:
      - '4000:4000'

  nginx:
    image: kanadome/hackathon_vol8_team21-nginx:latest
    build:
      context: ./
      dockerfile: infra/dockerfiles/prod/nginx.Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network
    restart: always
    depends_on:
      - frontend

volumes:
  mysql-db:
    driver: local

networks:
  app-network:
    driver: bridge