version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
      
  backend:
    tty: true
    depends_on:
      - db
    build:
      context: ./ 
      dockerfile: infra/dockerfiles/local/backend.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  frontend:
    build:
      context: ./
      dockerfile: infra/dockerfiles/local/frontend.Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - '4000:4000'

  nginx:
    build:
      context: ./
      dockerfile: infra/dockerfiles/local/nginx.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - frontend

volumes:
  mysql-db:
    driver: local