  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
# ... existing code ...
      # Runs a single command using the runners shell
      - name: Notify push or pull request to dev
        if: github.ref == 'refs/heads/dev'
        run: echo "Pushed or pull request to dev branch"