name: EC2ログインテスト

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch: # 手動トリガーを追加

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: AWSの認証情報を設定
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  

    - name: EC2インスタンスにSSH接続
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << 'EOF'
          echo "EC2インスタンスに接続成功"
          git clone https://github.com/kanadomekei/hackathon_vol8_team21.git
          echo "リポジトリのクローンが完了しました。"
          cd hackathon_vol8_team21/
          git pull 
          cd frontend
          npm install
          cd ..
          docker compose -f docker-compose.local.yml up --build -d
        EOF
        rm private_key