name: Dev Branch Notification

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [closed]
    branches: [ "dev" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request was merged
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: echo "プルリクエストがdevブランチにマージされました。"

      - name: Notify push to dev
        if: github.event_name == 'push'
        run: echo "devブランチにプッシュされました。"